name: Test

# Trigger on any event related to issues.
on:
    issues:

env:
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./
